# ubuntu server 12.04 64bit with X-server installed
require "yaml"
sharing_config = YAML.load(File.open(File.join(File.dirname(__FILE__), "../../sharing.config.yaml"), File::RDONLY).read)

Vagrant.configure("2") do |config|

    config.vm.define :ubuntu_1204_x do |machine|
        # set up basic box image
        machine.vm.box = "ubuntu/precise64"

        # set host name
        machine.vm.hostname = "vagrant-x"
        machine.vm.network "private_network", ip: "192.168.50.7"

        # update machine configurations
        machine.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--memory", 4096]
            v.customize ["modifyvm", :id, "--cpus", 4]
        end

        # enable X11 forwarding
        machine.ssh.forward_x11 = true

        # install x11 for gui appliatins
        machine.vm.provision "shell", inline: "apt-get install -y xorg"

        # provision docker
        machine.vm.provision "docker"

        if sharing_config
            sharing_config.each { |key, value| value.each { |key_, value_| machine.vm.synced_folder key_, "/synced/" + key + key_ } }
        end
    end
end
