FROM harmishhk/ros:jade-desktop-full

# install extra packages required by spencer
RUN apt-get install -y \
    python-catkin-tools \
    libmrpt-dev \
    mrpt-apps \
    freeglut3-dev \
    libsvm-dev \
    ros-jade-navigation \
    ros-jade-cmake-modules \
    ros-jade-joy
