FROM harmishhk/ros:indigo-desktop-full

# install pr2 packages for indigo
RUN apt-get update
RUN apt-get install -y ros-indigo-pr2-common ros-indigo-pr2-mechanism ros-indigo-pr2-navigation ros-indigo-pr2-simulator ros-indigo-pr2-tuckarm
