# ubuntu server 14.04 64bit
require "yaml"
sharing_config = YAML.load(File.open(File.join(File.dirname(__FILE__), "../sharing.config.yaml"), File::RDONLY).read)

Vagrant.configure("2") do |config|

    config.vm.define :ubuntu_1404 do |machine|
        # set up basic box image
        machine.vm.box = "ubuntu/trusty64"

        # set host name
        machine.vm.hostname = "vagrant"
        machine.vm.network "private_network", ip: "192.168.50.4"

        # update machine configurations
        machine.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--memory", 12288]
            v.customize ["modifyvm", :id, "--cpus", 8]
        end

        # provision docker
        machine.vm.provision "docker"

        if sharing_config
            sharing_config.each { |key, value| value.each { |key_, value_| machine.vm.synced_folder key_, "/synced/" + key + key_ } }
        end
    end
end
