# base ubuntu desktop 14.04 64bit (needs locally stored vm image)
require "yaml"
sharing_config = YAML.load(File.open(File.join(File.dirname(__FILE__), "../../sharing.config.yaml"), File::RDONLY).read)

Vagrant.configure("2") do |config|

    config.vm.define :ubuntu_1404_desktop do |machine|
        # set up basic box image (from local images)
        machine.vm.box = "ubuntu-1404-desktop"

        # set host name
        machine.vm.hostname = "vagrant-desktop"
        machine.vm.network "private_network", ip: "192.168.50.6"

        # update machine configurations
        machine.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--memory", 4096]
            v.customize ["modifyvm", :id, "--cpus", 4]
        end

        # enable X11 forwarding
        machine.ssh.forward_x11 = true

        # provision docker
        machine.vm.provision "docker"

        if sharing_config
            sharing_config.each { |key, value| value.each { |key_, value_| machine.vm.synced_folder key_, "/synced/" + key + key_ } }
        end
    end
end
