FROM    harmishhk/nvidia

MAINTAINER harmish khambhaita <harmish@laas.fr>

# install morse and python bindings
RUN apt-get update
RUN apt-get install -y \
    morse-simulator \
    python3-morse-simulator
