# docker image of ubuntu server 14.04 with ros-indigo-desktop-full installed, running inside ubuntu server 14.04 vagrant machine
require "yaml"
sharing_config = YAML.load(File.open(File.join(File.dirname(__FILE__), "../../sharing.config.yaml"), File::RDONLY).read)

Vagrant.configure("2") do |config|

    ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

    config.vm.hostname = "ros-indigo-devel"

    config.vm.provider "docker" do |d|
        d.force_host_vm = true
        d.build_dir = "."
        d.build_args = ["--tag=local:ros-indigo-devel"]
        d.vagrant_vagrantfile = "../../vagrant/ubuntu-1404/Vagrantfile"
        d.has_ssh = true

        if sharing_config && sharing_config[config.vm.hostname]
            sharing_config[config.vm.hostname].each { |key, value| d.create_args += ["--volume=/synced/" + config.vm.hostname + key + ":" + value]}
        end
    end
end
