FROM harmishhk/ros:hydro-desktop-full

# install extra packages required by navigation
RUN apt-get install -y \
    python-catkin-tools \
    libmrpt-dev \
    mrpt-apps \
    freeglut3-dev \
    libsvm-dev \
    ros-hydro-navigation \
    ros-hydro-cmake-modules \
    ros-hydro-joy
